spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13310/jpashop
    username: jpashop\
    init:
      mode: always
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  application:
    name: jpashop